version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ai-network

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi-ai
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
