# .github/workflows/deploy_ai.yml
name: Deploy AI Server to EC2

on:
  push:
    branches:
      - main   # 필요하다면 dev 등 다른 브랜치도 추가

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2) SSH 키를 ssh-agent에 로드
      - name: Load SSH key into ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      # 3) EC2에 SSH로 접속해서 배포 스크립트 실행
      - name: SSH & Deploy AI Server
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /home/ubuntu/final_project_ai

            echo "[1] Pull latest code"
            git pull origin main

            echo "[2] Stop existing containers"
            docker-compose down || true

            echo "[3] Build & start services"
            docker-compose up --build -d

            echo "[4] Deployment finished"
          EOF
